services:
  serviceA:
    image: golang:1.23.6
    volumes:
      - ./serviceA:/workspaces:cached
    working_dir: /workspaces/cmd/app
    command: go run main.go
    ports:
      - 8000:8000
    networks:
      - my_network
    depends_on:
      - serviceB
      - zipkin
    restart: unless-stopped

  serviceB:
    image: golang:1.23.6
    volumes:
      - ./serviceB:/workspaces:cached
    working_dir: /workspaces/cmd/app
    command: go run main.go
    networks:
      - my_network
    depends_on:
      - zipkin
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
